# Build Classification Models

In [1]:
import pandas as pd
cuisines_df = pd.read_csv("../data/cleaned_cuisines.csv")
cuisines_df.head()

,Unnamed: 0,cuisine,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,indian,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, precision_score, confusion_matrix, classification_report, precision_recall_curve
from sklearn.svm import SVC
import numpy as np

In [3]:
cuisines_label_df = cuisines_df["cuisine"]
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: str

In [4]:
cuisined_feature_df = cuisines_df.drop(["cuisine", "Unnamed: 0"], axis=1)
cuisined_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [5]:
X_train, X_test, y_train, y_test = train_test_split(cuisined_feature_df, cuisines_label_df, test_size=0.3, random_state=42)

In [8]:
lr = LogisticRegression(solver="lbfgs")
model = lr.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(f"accuracy {accuracy}")

accuracy 0.7956630525437864

In [9]:
print(f'ingredients: {X_test.iloc[50][X_test.iloc[50]!=0].keys()}')
print(f'cuisine: {y_test.iloc[50]}')

ingredients: Index(['coriander', 'cumin', 'fenugreek', 'pepper', 'soy_sauce', 'turmeric'], dtype='str')
cuisine: thai

In [11]:
test = X_test.iloc[50].values.reshape(-1, 1).T
proba = model.predict_proba(test)
classes = model.classes_

resultdf = pd.DataFrame(data=proba, columns=classes)
topPredictions = resultdf.T.sort_values(by=[0], ascending=[False])
topPredictions.head()

/home/wojciech_wladzinski/programming/ML-For-Beginners/.venv/lib64/python3.14/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

                 0
thai      0.568730
japanese  0.239152
indian    0.097863
chinese   0.088808
korean    0.005446

In [12]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

     chinese       0.73      0.70      0.71       236
      indian       0.90      0.91      0.90       245
    japanese       0.72      0.77      0.75       231
      korean       0.80      0.75      0.78       242
        thai       0.82      0.85      0.84       245

    accuracy                           0.80      1199
   macro avg       0.79      0.79      0.79      1199
weighted avg       0.80      0.80      0.80      1199